baseURL = "https://AngelSalazar-11.github.io/auras-site/"
languageCode = "es-mx"
title = "Aura S."
theme = "aura"
paginate = 20

[taxonomies]
  type = "type"
  collection = "collection"

[params]
  author = "Aura S."
  description = "Escritura"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
  [markup.highlight]
    noClasses = false
